version: '3'

networks:
  monreseau:
    external: false

services:

  db:

    image: 'postgres'

    container_name: fewnu_postgres

    restart: always

    environment:
      - POSTGRES_DB=docker
      - POSTGRES_USER=sultan
      - POSTGRES_PASSWORD=jepasse

    networks:
      - monreseau

    volumes:
      - postgres-data:/var/lib/postgresql/data

  web:  

    build: .

    container_name: fewnu_app

    restart: always

    ports:
      - "8000:8000"

    networks:
      - monreseau

    volumes:
      - sitestatics:/usr/src/app/static_assets/                                                                                                                                                                                     
      - sitemedias:/usr/src/app/medias/

    depends_on:
      - db
    # command: ["python3","manage.py","runserver"]
    # command: ["./docker-entrypoint.sh"]

    links:
      - "db:database"

  nginx:

    build: ./nginx

    container_name: fewnu_nginx

    networks:
      - monreseau

    volumes:
      - sitestatics:/home/app/web/staticfiles
      - sitemedias:/home/app/web/mediafiles
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro  

    depends_on:
      - web

    ports:
      -  89:89
      -  443:443
  certbot:
      image: certbot/certbot:latest
      volumes:
        - ./certbot/www/:/var/www/certbot/:rw
        - ./certbot/conf/:/etc/letsencrypt/:rw

volumes:
    postgres-data:   
    sitestatics:
    sitemedias:
