# Generated by Django 3.2.22 on 2023-11-09 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='mesure_title',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
