# Generated by Django 4.1.3 on 2023-09-13 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_fewnu_compta', '0028_alter_transaction_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='mesure_client',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
    ]
